FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./packages/server/package*.json ./packages/server/

RUN npm ci -w packages/server

COPY ./packages/server ./packages/server

RUN npm run build -w packages/server

EXPOSE 4000

CMD [ "node", "packages/server/dist/app.js" ]